using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

//TODO:DEV
//SQL-näkymällä saa tulostettua ajatasaisen listan
//Näkymä löytyy nimellä app.vGeoServiceFeatureFlags

namespace GeoService_UI.Models
{
    public enum GeoServiceFeatureFlags
    {
        ApiAgentti,
        ApiAgenttiLoki,
        ApiAjastus,
        ApiAjo,
        ApiAnalytiikka,
        ApiAppLoki,
        ApiAsetukset,
        ApiAsiakas,
        ApiBoxAndWhisker,
        ApiEtusivu,
        ApiFIST,
        ApiKoodi,
        ApiKoodiryhma,
        ApiLoki,
        ApiMallirekisteri,
        ApiMrEepos,
        ApiMrEeposKonteksti,
        ApiMrEeposMittaus,
        ApiMrEntiteettitaso,
        ApiMrMalli,
        ApiMrTiedosto,
        ApiMrTyyppi,
        ApiOhje,
        ApiPalvelupaketti,
        ApiPalvelupakettiSisalto,
        ApiProfiili,
        ApiProjekti,
        ApiProsessitaulu,
        ApiRaportti,
        ApiRooli,
        ApiRooliOikeudet,
        ApiRoolit,
        ApiTehtava,
        ApiTila,
        ApiToiminnot,
        ApiToiminto,
        ApiTyo,
        UiAgentti,
        UiAgenttiLoki,
        UiAjastus,
        UiAjo,
        UiAnAjo,
        UiAnalytiikka,
        UiAnKulutus,
        UiAppLoki,
        UiAsetukset,
        UiAsiakas,
        UiBoxAndWhisker,
        UiEtusivu,
        UiFIST,
        UiKoodi,
        UiKoodiryhma,
        UiLoki,
        UiMallirekisteri,
        UiMrEepos,
        UiMrEeposKonteksti,
        UiMrEeposMittaus,
        UiMrEntiteettitaso,
        UiMrMalli,
        UiMrTiedosto,
        UiMrTyyppi,
        UiOhje,
        UiPalvelupaketti,
        UiPalvelupakettiSisalto,
        UiProfiili,
        UiProjekti,
        UiProsessitaulu,
        UiRaportti,
        UiRooli,
        UiRooliOikeudet,
        UiRoolit,
        UiTehtava,
        UiTila,
        UiToiminnot,
        UiToiminto,
        UiTyo
    }
}
